use rustate::{state_machine, StateMachine, StateMachineDef};

// Define a simple context (can be () if not needed)
type TrafficLightContext = ();

state_machine! {
    // The state machine definition using rustate syntax
    // Note: Derives needed for visualizer (Clone, Copy, PartialEq, Eq, Hash, Debug)
    derive(Clone, Copy, PartialEq, Eq, Hash, Debug)
    pub TrafficLight(initial = State::Red) {
        // Define states
        State::Red => {
            Event::TimerElapsed => State::Green,
        },
        State::Green => {
            Event::TimerElapsed => State::Yellow,
        },
        State::Yellow => {
            Event::TimerElapsed => State::Red,
        },
    }
}

/// Structure to hold transition info, simplified for the visualizer.
#[derive(Debug, Clone, PartialEq)]
pub struct VizTransition {
    pub from: traffic_light::State,
    pub event: traffic_light::Event,
    pub to: traffic_light::State,
}

/// Returns the definition of the traffic light state machine for visualization.
/// Uses the constants generated by the rustate macro.
pub fn get_traffic_light_definition() -> (Vec<traffic_light::State>, Vec<VizTransition>) {
    let states = traffic_light::StateMachineDef::STATES.to_vec();

    // Convert rustate's transition definition into a simpler format for the visualizer
    let transitions = traffic_light::StateMachineDef::TRANSITIONS
        .iter()
        .map(|t| VizTransition {
            from: t.from,
            event: t.event,
            to: t.to,
        })
        .collect();

    (states, transitions)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustate::StateMachine;

    #[test]
    fn it_works_rustate() {
        let mut machine = traffic_light::StateMachine::new(TrafficLightContext::default());
        assert_eq!(machine.state(), &traffic_light::State::Red);

        // rustate uses handle method
        let result = machine.handle(&traffic_light::Event::TimerElapsed);
        assert!(result.is_ok());
        assert_eq!(machine.state(), &traffic_light::State::Green);

        let result = machine.handle(&traffic_light::Event::TimerElapsed);
        assert!(result.is_ok());
        assert_eq!(machine.state(), &traffic_light::State::Yellow);

        let result = machine.handle(&traffic_light::Event::TimerElapsed);
        assert!(result.is_ok());
        assert_eq!(machine.state(), &traffic_light::State::Red);
    }

    #[test]
    fn definition_matches_rustate() {
        let (states, transitions) = get_traffic_light_definition();
        assert_eq!(states.len(), 3);
        assert!(states.contains(&traffic_light::State::Red));
        assert!(states.contains(&traffic_light::State::Green));
        assert!(states.contains(&traffic_light::State::Yellow));

        assert_eq!(transitions.len(), 3);
        // Check one transition as an example
        let expected_transition = VizTransition {
            from: traffic_light::State::Red,
            event: traffic_light::Event::TimerElapsed,
            to: traffic_light::State::Green,
        };
        assert!(transitions.contains(&expected_transition));
    }
} 