pub mod actor;
pub mod actor_ref;
pub mod logic;
pub mod simple_counter;
pub mod spawn;
pub mod system;

// 公開するものを選択
pub use actor::{Actor, ActorError};
pub use actor_ref::ActorRef;
pub use logic::ActorLogic;
pub use spawn::spawn;
pub use system::ActorSystem;

#[cfg(test)]
mod tests {
    use super::*;
    use simple_counter::{CounterActor, CounterEvent};
    use tokio::time::{sleep, Duration};

    // --- Test for original counter actor ---
    #[tokio::test]
    async fn test_counter_actor_with_system() {
        println!("Creating ActorSystem...");
        let system = ActorSystem::new("test-system");
        println!("ActorSystem created: {:?}", system);

        println!("Spawning CounterActor using system...");
        let counter_ref = system.spawn_default(CounterActor::default());
        println!("CounterActor spawned with ref: {:?}", counter_ref);

        sleep(Duration::from_millis(10)).await;

        println!("Sending Increment event...");
        let res1 = counter_ref.send(CounterEvent::Increment).await;
        assert!(res1.is_ok());
        println!("Increment event sent.");

        sleep(Duration::from_millis(10)).await;

        println!("Sending Increment event again...");
        let res2 = counter_ref.send(CounterEvent::Increment).await;
        assert!(res2.is_ok());
        println!("Increment event sent.");

        sleep(Duration::from_millis(10)).await;

        println!("Sending Print event...");
        let res3 = counter_ref.send(CounterEvent::Print).await;
        assert!(res3.is_ok());
        println!("Print event sent.");

        sleep(Duration::from_millis(50)).await;

        // TODO: Add assertions using an 'ask' pattern
        println!("Original counter test finished. Check logs for actor output.");
    }

    // --- Tests for the create_machine macro ---
    mod machine_macro_tests {
        // Move macro-specific imports inside this module
        use crate::logic::ActorLogic;
        use crate::actor::ActorError;
        use rustate_macros::create_machine; // Use the macro here
        use serde::{Deserialize, Serialize}; // Use serde here if needed by derives (though not directly used)
        // async_trait is needed by the code generated by the macro, but not directly used here

        // 1. Define types WITHIN this module scope
        #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)] // Added Serialize/Deserialize
        enum TestState {
            Idle,
            Running,
            Finished,
        }

        #[derive(Debug, Clone, Serialize, Deserialize)] // Added Serialize/Deserialize
        enum TestEvent {
            Start,
            Finish,
            Reset,
        }

        #[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)] // Added Serialize/Deserialize
        struct TestContext {
            count: i32,
        }

        // 2. Use the macro WITHIN this module scope
        create_machine!(
            MyTestMachine, // This struct is now local to machine_macro_tests
            Context = TestContext,
            Event = TestEvent,
            State = TestState,
            initial: TestState::Idle { count: 0 },
            states: {
                Idle { on: { Start: "Running" } },
                Running { on: { Finish: "Finished", Reset: "Idle" } },
                Finished { on: { Reset: "Idle" } }
            }
        );

        // 3. Write test functions WITHIN this module scope
        #[test]
        fn test_initial_state_and_context() {
            let machine = MyTestMachine::default(); 
            let (initial_state, initial_context) = machine.initial();
            assert_eq!(initial_state, TestState::Idle);
            assert_eq!(initial_context, TestContext { count: 0 });
        }

        #[tokio::test]
        async fn test_transitions() {
            let machine = MyTestMachine::default();
            let initial_context = TestContext { count: 0 }; // Start with default context

            // Test Idle -> Running
            let (next_state, next_context) = machine
                .transition(TestState::Idle, initial_context.clone(), TestEvent::Start)
                .await
                .expect("Transition failed");
            assert_eq!(next_state, TestState::Running);
            assert_eq!(next_context, initial_context); // Context shouldn't change yet

            // Test Running -> Finished
            let (next_state, next_context) = machine
                .transition(
                    TestState::Running,
                    initial_context.clone(),
                    TestEvent::Finish,
                )
                .await
                .expect("Transition failed");
            assert_eq!(next_state, TestState::Finished);
            assert_eq!(next_context, initial_context);

            // Test Running -> Idle (Reset)
            let (next_state, next_context) = machine
                .transition(
                    TestState::Running,
                    initial_context.clone(),
                    TestEvent::Reset,
                )
                .await
                .expect("Transition failed");
            assert_eq!(next_state, TestState::Idle);
            assert_eq!(next_context, initial_context);

            // Test Finished -> Idle
            let (next_state, next_context) = machine
                .transition(
                    TestState::Finished,
                    initial_context.clone(),
                    TestEvent::Reset,
                )
                .await
                .expect("Transition failed");
            assert_eq!(next_state, TestState::Idle);
            assert_eq!(next_context, initial_context);

            // Test no transition (e.g., Start event in Finished state)
            let (next_state, next_context) = machine
                .transition(
                    TestState::Finished,
                    initial_context.clone(),
                    TestEvent::Start,
                )
                .await
                .expect("Transition failed");
            assert_eq!(next_state, TestState::Finished); // Should remain in Finished
            assert_eq!(next_context, initial_context);

            // Test no transition (e.g., Reset event in Idle state)
            let (next_state, next_context) = machine
                .transition(TestState::Idle, initial_context.clone(), TestEvent::Reset)
                .await
                .expect("Transition failed");
            assert_eq!(next_state, TestState::Idle); // Should remain in Idle
            assert_eq!(next_context, initial_context);
        }
    } // End of machine_macro_tests module

    // --- Remove or comment out the other potentially problematic/redundant test modules ---
    /*
    mod simple_macro_gen_test { ... }
    mod spawn_generated_test { ... }
    */
} // End of tests module
