use yew::prelude::*;
use wasm_bindgen::prelude::*;
// Import from rustate_core using the new structure based on rustate
use rustate_core::traffic_light; // The module generated by state_machine!
use rustate_core::{get_traffic_light_definition, VizTransition, TrafficLightContext}; // Import the helper function and transition struct
use rustate::StateMachine; // Import the StateMachine trait from rustate
use std::collections::HashMap;

// --- SVG Constants ---
const SVG_WIDTH: i32 = 600;
const SVG_HEIGHT: i32 = 400;
const STATE_RADIUS: i32 = 30;
const STATE_COLOR: &str = "lightblue";
const CURRENT_STATE_COLOR: &str = "lightcoral";
const TRANSITION_COLOR: &str = "gray";
const TEXT_COLOR: &str = "black";
const ARROW_ID: &str = "arrowhead";

// --- Data Structures ---

#[derive(Properties, PartialEq)]
pub struct Props {}

pub enum Msg {
    NextState,
}

pub struct App {
    machine: traffic_light::StateMachine<TrafficLightContext>,
    states: Vec<traffic_light::State>,
    transitions: Vec<VizTransition>, // Use VizTransition
    state_positions: HashMap<traffic_light::State, (i32, i32)>,
}

// --- Helper Functions ---

/// Calculate positions for states (simple circular layout)
fn calculate_state_positions(states: &[traffic_light::State]) -> HashMap<traffic_light::State, (i32, i32)> {
    let mut positions = HashMap::new();
    let n = states.len();
    if n == 0 {
        return positions;
    }
    let center_x = SVG_WIDTH / 2;
    let center_y = SVG_HEIGHT / 2;
    let layout_radius = std::cmp::min(SVG_WIDTH, SVG_HEIGHT) / 3;

    for (i, state) in states.iter().enumerate() {
        let angle = 2.0 * std::f64::consts::PI * (i as f64) / (n as f64) - std::f64::consts::FRAC_PI_2;
        let x = center_x + (layout_radius as f64 * angle.cos()) as i32;
        let y = center_y + (layout_radius as f64 * angle.sin()) as i32;
        positions.insert(*state, (x, y));
    }
    positions
}

/// Calculate points for the transition line between two states
fn calculate_transition_points(start_pos: (i32, i32), end_pos: (i32, i32), radius: i32) -> ((i32, i32), (i32, i32)) {
    let dx = (end_pos.0 - start_pos.0) as f64;
    let dy = (end_pos.1 - start_pos.1) as f64;
    let dist = (dx * dx + dy * dy).sqrt();
    if dist < 1e-6 { // Avoid division by zero if positions are the same
        return (start_pos, end_pos);
    }

    let ratio_start = radius as f64 / dist;
    let ratio_end = (dist - radius as f64) / dist;

    let p1_x = start_pos.0 + (dx * ratio_start) as i32;
    let p1_y = start_pos.1 + (dy * ratio_start) as i32;
    let p2_x = start_pos.0 + (dx * ratio_end) as i32;
    let p2_y = start_pos.1 + (dy * ratio_end) as i32;

    ((p1_x, p1_y), (p2_x, p2_y))
}

// --- Yew Component Implementation ---

impl Component for App {
    type Message = Msg;
    type Properties = Props;

    fn create(_ctx: &Context<Self>) -> Self {
        let (states, transitions) = get_traffic_light_definition();
        let state_positions = calculate_state_positions(&states);
        Self {
            // Initialize rustate StateMachine with context
            machine: traffic_light::StateMachine::new(TrafficLightContext::default()),
            states,
            transitions, // Already using VizTransition from core
            state_positions,
        }
    }

    fn update(&mut self, _ctx: &Context<Self>, msg: Self::Message) -> bool {
        match msg {
            Msg::NextState => {
                // Use rustate's handle method
                let _result = self.machine.handle(&traffic_light::Event::TimerElapsed);
                // We ignore the result for this simple example, but you might want to check it
                true // Re-render needed
            }
        }
    }

    fn view(&self, ctx: &Context<Self>) -> Html {
        let link = ctx.link();
        // Get state using rustate's state() method
        let current_machine_state = *self.machine.state();

        let svg_states = self.states.iter().map(|state| {
            let (cx, cy) = self.state_positions.get(state).unwrap_or(&(0, 0));
            let fill_color = if *state == current_machine_state { CURRENT_STATE_COLOR } else { STATE_COLOR };
            // State enum likely generated by rustate macro
            let state_label = format!("{:?}", state);
            html! {
                <>
                    <circle cx={cx.to_string()} cy={cy.to_string()} r={STATE_RADIUS.to_string()} fill={fill_color} stroke={TEXT_COLOR} stroke-width="1" />
                    <text x={cx.to_string()} y={cy.to_string()} dy=".3em" text-anchor="middle" fill={TEXT_COLOR} font-size="12">
                        { state_label }
                    </text>
                </>
            }
        }).collect::<Html>();

        let svg_transitions = self.transitions.iter().map(|transition| {
            let start_pos = self.state_positions.get(&transition.from).unwrap_or(&(0, 0));
            let end_pos = self.state_positions.get(&transition.to).unwrap_or(&(0, 0));
            let ((x1, y1), (x2, y2)) = calculate_transition_points(*start_pos, *end_pos, STATE_RADIUS);
            // Event label - access the event field from VizTransition
            let event_label = format!("{:?}", transition.event);
            // Calculate midpoint for the label
            let mid_x = (x1 + x2) / 2;
            let mid_y = (y1 + y2) / 2;
            html! {
                <>
                    <line x1={x1.to_string()} y1={y1.to_string()} x2={x2.to_string()} y2={y2.to_string()} stroke={TRANSITION_COLOR} stroke-width="2" marker-end={format!("url(#{})", ARROW_ID)} />
                    <text x={mid_x.to_string()} y={mid_y.to_string()} dy="-5" text-anchor="middle" fill={TEXT_COLOR} font-size="10">
                        { event_label }
                    </text>
                </>
            }
        }).collect::<Html>();

        html! {
            <div>
                <h1>{ "Traffic Light State Machine (SVG with rustate)" }</h1>
                <svg width={SVG_WIDTH.to_string()} height={SVG_HEIGHT.to_string()} style="border: 1px solid black;">
                    <defs>
                        <marker id={ARROW_ID} viewBox="0 0 10 10" refX="8" refY="5"
                            markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                            <path d="M 0 0 L 10 5 L 0 10 z" fill={TRANSITION_COLOR} />
                        </marker>
                    </defs>
                    { svg_transitions }
                    { svg_states }
                </svg>
                <p>{ format!("Current State: {:?}", current_machine_state) }</p>
                <button onclick={link.callback(|_| Msg::NextState)}>{ "Next State" }</button>
            </div>
        }
    }
}

#[wasm_bindgen(start)]
pub fn run_app() {
    yew::Renderer::<App>::new().render();
} 